name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_f917cb2e-39f6-4dee-b9c3-2f90a6f60045
          GH_TOKEN: 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
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_OS: "True"
          LOCALE: "en"
          
